### ISSUE TITLE
Fix Checkstyle Issues and Build process

### ISSUE THREAD

**Issue by PhilMFischer** [virtualsatellite/VirtualSatellite4-Core#1063]
Checkstyle is identifying a lot of new issues.

The build process is not catching them.

This needs to be aligned.

**Comment by maurpa** [comment]
There seems also to be a vulnerability concering checkstyle in  com.puppycrawl.tools:checkstyle 
https://github.com/virtualsatellite/VirtualSatellite4-Core/security/dependabot/1
