### ISSUE TITLE
Write developer manual

### ISSUE THREAD

**Issue by PhilMFischer** [virtualsatellite/VirtualSatellite4-Core#111]
Same as the user manual, we need a developer manual. The manual should focus on using our Virtual Satellite 4 IDE to write your own concept. The manual does not cover general Virtual Satellite 4 development.

**Comment by PhilMFischer** [comment]
First manual introduced by #278.

**Comment by SaMuellerDLR** [comment]
Make individual concrete tickets when progressing on this.
