### ISSUE TITLE
Serving of OpenAPI spec

### ISSUE THREAD

**Issue by dellerDLR** [virtualsatellite/VirtualSatellite4-Core#1169]
**Description**
The OpenAPI spec is not served at the moment.
Also it is project specific. From my point of view it is not project specific.

**Comment by dellerDLR** [comment]
The spec file can be served via the following url:
localhost:8000/rest/model/v0.0.1/swagger.json

But it does not get generated atm

**Comment by dellerDLR** [comment]
Swagger plugin is defined in the pom.xml of the server project, but could not find a way to trigger it manually:

https://github.com/virtualsatellite/VirtualSatellite4-Core/blob/4666e4a8f837466efaf1b17f2e2d6305c121e105/de.dlr.sc.virsat.server/pom.xml#L21

**Comment by franzTobiasDLR** [comment]
Fixed with Release 4.17.0
