### ISSUE TITLE
Release Version 4.18.0 

### ISSUE THREAD

**Issue by shapelessguy** [virtualsatellite/VirtualSatellite4-Core#1236]
Virtual Satellite Release Version 4.18.0

This ticket captures all release related work of VirtualSatellite4-Core

1. Perform version update:
- [x] Checkout/Update the `Development` branch
- [x] Remove current `integration` branch (Make sure no one else is integrating at the moment) 
- [x] Create new `integration` branch from development branch
- [x] Run ant script to update version numbers (open build.xml and start the updateVersions task)
- [x] Check if the server APIs had changes and update the version numbers in the servlets if necessary
- [x] Check if there are unreleased changes on the Ecore data model (open dvlm.ecore, check if History > Release (not yet released is empty))
- [x] Check that Java API Doc is working in our Concept-IDE - If not update the Java API Doc being registered in the Java doc plugin
    - To check if it works, create a VirSat App and test if the Java API and Model APi from VirSat is backed by JavaDoc
- [x] Make sure application launches without errors from the product launcher
- [x] Merge `integration` branch into `development` branch (Pull Request named "Integration 4.18.0 - Remerge Versions")

2. Perform integration on integration branch:
- [x] Apply all needed fixes
- [x] Update the release notes

3. Update master/release branch:
- [x] Merge `integration` branch into `master` branch (Pull Request named "Release 4.18.0")
- [x] Create GitHub Release including a Tag on the 'master' branch. Name it "Release_4.18.0".

4. Merge back integration branch:
- [x] Merge `integration` branch into `development` branch (Pull Request named "Integration 4.18.0 - Remerge Fixes")
 
Well Done!! You should have a new Virtual Satellite Release :rocket:

**Comment by PhilMFischer** [comment]
Closes #1214
