### ISSUE TITLE
Requirement concept ReqIF builder

### ISSUE THREAD

**Issue by franzTobiasDLR** [virtualsatellite/VirtualSatellite4-Core#131]
Builder that automatically keeps ReqIF files up-to-date

**Comment by SaMuellerDLR** [comment]
@franzTobiasDLR I think I remember the requirements concept having some sort of verification builder. Is this ticket still up to date?

**Comment by franzTobiasDLR** [comment]
Yes, the verification build is about constanty verifying requirements; the ReqIF build is about maintaing a ReqIF reprensentation of our requirements data. However, I'm not sure if it isn't enough to import and export in manually....

**Comment by franzTobiasDLR** [comment]
Oh, looks like I actually developed stuff for that ticket... I guess it was not merged ^^

**Comment by SaMuellerDLR** [comment]
Was used as a reference branch for future development. Will probably no longer contribute anything and reqif builder will probably not be needed.
