### ISSUE TITLE
Check inheritance of cardinality one categories without common ancestor.

### ISSUE THREAD

**Issue by PhilMFischer** [virtualsatellite/VirtualSatellite4-Core#140]
Related to #132 .

Inheriting a category with cardinality one, in a diamond inheritance should always inherit from the lasr one in the inheritance list. and don't obey the first inheritance. This is fixed in #132.

For two category assignments with cardinality one which do not have a common ancestor, and therefore would create two category assignments in the inheriting StructuralElementInstance, also the first one from the InheritanceList should be obeyed. This is not yet checked.

**Comment by PhilMFischer** [comment]
We should still discuss, if this is consistent with general inheritance behaviout. We should clarify which category is the one that should be copied. The one from the first palce of inheitance or the one from the last place of inheitance.

**Comment by SaMuellerDLR** [comment]
Should have a test case.
