### ISSUE TITLE
Add section for CATIA import / export in User Guide

### ISSUE THREAD

**Issue by SaMuellerDLR** [virtualsatellite/VirtualSatellite4-Core#152]
The user guide should explain how to use the CATIA import / export functionality.
It should also explain how to setup the Visual Basic scripts in CATIA.

**Comment by JAmmermann-DLR** [comment]
Discussed with @andriikovalov-dlr  that "CATIA" should be renamed to the more general term "CAD" and therefore also in the user guide. 

Also no explanation of the CATIA implementation (Visual Basic) should be given at the moment.
