### ISSUE TITLE
License conform SVNKit Integration

### ISSUE THREAD

**Issue by PhilMFischer** [virtualsatellite/VirtualSatellite4-Core#203]
Virtual Satellite is heavily based on Subversion to perform mdoel exchange. To develop and test the software, it is necessary to install the SvnKit. Due to license issues it cannot be shipped with Virtual Satellite. Stills etting up the workspace enivronment is very difficult without SVN Kit.

**Comment by andriikovalov-dlr** [comment]
According to SVNKit support, there is no license issue in delivering SVNKit with the application.
