### ISSUE TITLE
Create a mechanism to specify abstract levels

### ISSUE THREAD

**Issue by franzTobiasDLR** [virtualsatellite/VirtualSatellite4-Core#241]
Create a mechanism to handle elements at different levels within a tree. Such a mechanism should check to which level a passed object might belong to. 

This is necessary because category assignments applicability can only be specified to what type of structural element... not at which depth level within a tree. 

An example for such a mechanism is that some model elements should be only applicable on e.g.
- global system level, 
- some at sub system level and some at 
- equipment level. 

As we do not have explicit structural elements for system, sub system and equipment we need a mechanism that allows us to customize handlers, commands and table viewers to only show relevant aspects of the model elements.

In the before mentioned example System, Subsystem and Equipment are considered as levels. They should be an implementation of an abstract level and e.g. specify which CAs are applicable considering the current tree depth level and CAs of other levels which are already modeled.

**Comment by PhilMFischer** [comment]
Please explain why this is needed and give an example what is meant by abstract levels.
