### ISSUE TITLE
Improve spelling/grammar in user manual

### ISSUE THREAD

**Issue by Anna-Lena-DLR** [virtualsatellite/VirtualSatellite4-Core#296]
- Corrected spelling mistakes in different sections (missing full stops, wrong spelling)
- Changed term ("apply" instead of "assign") because GUI uses other term

**Comment by SaMuellerDLR** [comment]
@Anna-Lena-DLR  Please give a more descriptive title & description.
Otherwise all tickets that iterate on the user manual will look too much the same.
