### ISSUE TITLE
Generate test class for generated concept validator 

### ISSUE THREAD

**Issue by franzTobiasDLR** [virtualsatellite/VirtualSatellite4-Core#305]
The concept generator creates a default validation class (A)StructuralElementInstanceValidator. 
There is, however, no coresponding test class genrated. This decreases test coverage.

-> In the test plugin fragement, there should be a package <concept>.validator with a generated test class for this generated validator.

Structure should be similar to the generation of the migrator test class...

**Comment by Anna-Lena-DLR** [comment]
closes with #350
