### ISSUE TITLE
forcedUser doesn't work in compiled VirSat

### ISSUE THREAD

**Issue by andriikovalov-dlr** [virtualsatellite/VirtualSatellite4-Core#36]

**Comment by SaMuellerDLR** [comment]
@andriikovalov-dlr please give more information (e.g. concrete configuration file)

**Comment by andriikovalov-dlr** [comment]
Steps to reproduce:

1. Download VirSat release from github
2. Add a following line to the end of the VirSat4_Core.ini `-forcedUser some_user`
3. Start Virsat, create a project, open User Management

**Expected:**
I see a message in the Disciplines table that I am logged in as some_user
**Actual:**
I see a message that I am logged in as my windows user
Also there is a message in the log `CommandLine Argument is not understood: -forcedUser some_user`

**Comment by SaMuellerDLR** [comment]
forcedUser doesnt work at the end of the ini file since its interpreted as a VM argument instead of a VirSat argument. It should be at the beginning of the ini file.

**Comment by andriikovalov-dlr** [comment]
Still doesn't work for me if I put -forcedUser in the beginning. On the other hand, -superUser flag works in the beginning and in the end of the file.
Here is my full ini file:
```
-forcedUser some_user
-startup
plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.551.v20171108-1834
-console
-consoleLog
```

**Comment by SaMuellerDLR** [comment]
@andriikovalov-dlr I just tried it out.
Works for me if you put some_user into a new line.

**Comment by andriikovalov-dlr** [comment]
@SaMuellerDLR right, this works for me too.
Okay, I think we can leave with it :)
