### ISSUE TITLE
Make the VirSat repository available via REST interface.

### ISSUE THREAD

**Issue by dianapeters-dlr** [virtualsatellite/VirtualSatellite4-Core#361]
Replaced by #532.

- [ ] create endpoints
- [ ] conversion of beans to json
- [ ] handle json input to manipulate beans

Closes with #532 since it provides some resonable code examples on how to deal with REST testing etc.

**Comment by SaMuellerDLR** [comment]
@PhilMFischer @JAmmermann-DLR Please check status
