### ISSUE TITLE
HotFix: Calculations stop silently on error

### ISSUE THREAD

**Issue by PhilMFischer** [virtualsatellite/VirtualSatellite4-Core#392]
The calculation engine stops silently on errors.

This needs to be improved to at least improve logging:

- [x] Improve logging
- [x] Check if UI feedback is possible as well.

Related to #387

**Comment by andriikovalov-dlr** [comment]
We will only write errors to log. UI feedback would require substantial changes to `VirSatProblemMarkerHelper` because it only supports adding markers to `EObject`, but not EMF `Resource`.
