### ISSUE TITLE
Extend UI Tests by Test Matrix

### ISSUE THREAD

**Issue by PhilMFischer** [virtualsatellite/VirtualSatellite4-Core#441]
Now where SWT Bot is more stable, UI testing can be extended.

- [ ] Tests for Repository Update and Commit Actions including data changes and discipline changes
- [ ] Add changes to CAs from Table Editors

**Comment by SaMuellerDLR** [comment]
Closed due to sprint project taking over https://github.com/virtualsatellite/VirtualSatellite4-Core/projects/6

**Comment by SaMuellerDLR** [comment]
Now https://github.com/orgs/virtualsatellite/projects/3
