### ISSUE TITLE
Multiple users per discipline

### ISSUE THREAD

**Issue by andriikovalov-dlr** [virtualsatellite/VirtualSatellite4-Core#463]
Add the possibility to assign multiple users to a discipline. If there is a merge conflict on commit, the local changes should be discarded (with a clear message to the user on what is being discarded).

Steps to be done:

- [ ] Update DVLM model

- [ ] Make sure generated code works in our UI

- [ ] Update UI to be able to add multiple users to discipline

**Comment by DimitriDiantos** [comment]
Implement custom dialog for assigning multiple users to a
discipline

Implement the CustomDialog class, extending the Dialog class to create a
custom dialog that allows user interaction to modify a list of users for
a discipline. The dialog provides functionality to add, remove, update,
move up, and move down users in the list. Additionally, an interface
FeatureUpdateCallback is defined to handle feature update callbacks.

Also, introduce EListStringCellEditingSupport to handle cell editing in
a table viewer for EList of strings in the context of editing a
Discipline.

Files affected:
- CustomDialog.java (new created file)
- FeatureUpdateCallback.java(new created file)
- EListStringCellEditingSupport.java (new created file)
- UiSnippetRoleManagement.java (exited file before the custom Dialog)
- EStringCellEditingSupport (existing before)
