### ISSUE TITLE
Dead Lock in Transactional Editing Domain on runExclusive

### ISSUE THREAD

**Issue by PhilMFischer** [virtualsatellite/VirtualSatellite4-Core#478]
Run exclusive does not execute and lock the workspace first. But, there is some code, which executes commands within this transaction. This creates an invers locking of transaction first and then the workspace. This can create deadlocks with e.g. builders.

**Comment by SaMuellerDLR** [comment]
Done in #479 (was incorrectly linked).
@PhilMFischer  please reopen if this is incorrect.
