### ISSUE TITLE
Inconsistency between the bean and the underlying CA

### ISSUE THREAD

**Issue by andriikovalov-dlr** [virtualsatellite/VirtualSatellite4-Core#486]
I have a bean A referencing a bean B with an array of C's.
I want to change B into B2, call `A.setB(B2)`, this changes the model, but doesn't update the internal reference in A (it still points to B).

Then I call `A.getB()`. This updates an old bean B with a new CA, but it doesn't reset the cached values for the array of C's. When I then call `A.getB().getCs()`, I get old C's from B, but not from B2.

**Comment by SaMuellerDLR** [comment]
@andriikovalov-dlr @JAmmermann-DLR Could you guys check how this works witht he new ReferencePropertyBean?

**Comment by SaMuellerDLR** [comment]
Maybe reproduce in extension.tests concept.

**Comment by andriikovalov-dlr** [comment]
New `ReferencePropertyBean` looks good - it doesn't cache anything (in contrast to arrays which causes this bug)
