### ISSUE TITLE
Add repositories to REST server

### ISSUE THREAD

**Issue by JAmmermann-DLR** [virtualsatellite/VirtualSatellite4-Core#493]
Virtual Satellite headless/server should provide capabilities to access several projects with one server. Therefore a repository within the server should represent one project in virtual satellite. A repository therefore needs to know from where to check out or access a repository. It needs credentials and a setting telling if it is a *svn* or *git* backend (functionality of #519). All repositories which are set-up should be restored when the server starts. All repositories should persist when the server stops. The location for storing and loading should be taken from the server configuration. For accessing the backend the repository has to use a functional account and password. The password should be stored encrypted. The repository has to also check, if the given user is allowed to access the repository.

- [ ] Add repositories with dummy svn/git connection
- [ ] Add a resource (for admins) to modify repositories
- [ ] Add a resource (for users) to access a specific repository
- [ ] Add repository authorization
- [ ] Store repositories to configured persistency location ( as set by #530)

Make sure when externally reading the repository via REST API, object, that it does not expose the password

Uses #376 as orientation.

**Comment by JAmmermann-DLR** [comment]
It may be more convenient to check if a user can access the repository (not the other way around) on server level using filters (see https://github.com/virtualsatellite/VirtualSatellite4-Core/issues/454).

**Comment by JAmmermann-DLR** [comment]
![new_concept_2](https://user-images.githubusercontent.com/56025440/77307980-86f44280-6cfa-11ea-85cf-0fd60af42d1e.png)

**Comment by PhilMFischer** [comment]
Split into two individual tickets #537 and #540.
