### ISSUE TITLE
Server configuration area

### ISSUE THREAD

**Issue by PhilMFischer** [virtualsatellite/VirtualSatellite4-Core#530]
The server needs a common configuration area and a common configuration file. Usually the standard configuration should be provided by the plugin resources. Additionally a user should have the possibility to start virtual satellite with a custom path which is sued for loading configurations. The logic should always be that the server first searches the user directory for settings, if it doesn't find any it falls back to the plugin default configurations.

- [x] Command line option to specify the configuration path
- [ ] Command line option to fill the configuration path with defaults
- [x] A java properties files with common settings for the server
- [x] A simple internal API as singleton close to the bundle activator to access configuration files

**Comment by andriikovalov-dlr** [comment]
Command line parameter for copying default configuration moved to #536
