### ISSUE TITLE
Improvement in RepoManagementController

### ISSUE THREAD

**Issue by andriikovalov-dlr** [virtualsatellite/VirtualSatellite4-Core#556]
- [x] Adding a project should create .properties file in the configs dir
- [x] Removing a project should remove its .properties file and maybe delete it completely
- [x] Updating a project should be handled properly (changing functional account / changing URI etc.)

**Comment by SaMuellerDLR** [comment]
@JAmmermann-DLR What is the state of this?

**Comment by JAmmermann-DLR** [comment]
> 
> 
> @JAmmermann-DLR What is the state of this?

The updating of a project has to be improved and tested
