### ISSUE TITLE
Evaluate transforming Beans from/to JSONs with Jersey

### ISSUE THREAD

**Issue by JAmmermann-DLR** [virtualsatellite/VirtualSatellite4-Core#607]
It should be tested if and how we can transform a bean from and to JSONs using Jersy.

If it is feasible it could be used for the REST server and/or the ModelAPI.

**Comment by PhilMFischer** [comment]
This task has some reference to #167 

For easy bean to json transformation jersey can be used. Nevertheless the current jersey dependency does not use the MOXy reference implementation for the bean to json transformation. This should be fixed before.
