### ISSUE TITLE
Cannot use SVN when starting VirSat from Eclipse

### ISSUE THREAD

**Issue by andriikovalov-dlr** [virtualsatellite/VirtualSatellite4-Core#65]
When I try to checkout a project from SVN, I get "SVN connector missing" error, when I try to open Help -> Install New Software, I gen the following error:

> Could not locate the running profile instance. The eclipse.p2.data.area and eclipse.p2.profile properties may not be set correctly in this application's config.ini file

**Comment by SaMuellerDLR** [comment]
Currently SVN plugin is not in the target platform to guarantee that its not shipped in the product.
Maybe make a filter list of "forbidden plugins" that should not be shipped and that is checked in the build process. Then SVN can be added to the target platform again.

**Comment by SaMuellerDLR** [comment]
Done in https://github.com/virtualsatellite/VirtualSatellite4-Core/issues/203
