### ISSUE TITLE
Unsetting a bean property by setting it to null

### ISSUE THREAD

**Issue by andriikovalov-dlr** [virtualsatellite/VirtualSatellite4-Core#675]
Currently to "unset" a property value, I need to do the following: `beanObject.getPropertyBean.unset()`
However, it would be nice if I could achieve the same effect by setting a property value to null: `beanObject.setProperty(null)`.

This should be done after #547

**Comment by SaMuellerDLR** [comment]
@andriikovalov-dlr Please add a description.

**Comment by SaMuellerDLR** [comment]
Wasn't needed the last two years, probably won't be needed. Reopen ticket if it turns out that this API is necessary.
