### ISSUE TITLE
Units for Thermal Applications

### ISSUE THREAD

**Issue by heibhe** [virtualsatellite/VirtualSatellite4-Core#729]
Some useful units for thermal applications are missing in the System Of Units:
1) Thermal Conductivity (in SI: Watt Per Meter And Kelvin, W m(^-1) K(^-1) )
2) Thermal Contact Resistance (in SI: Kelvin Per Watt, K W(^-1) )
3) Thermal Contact Conductance (in SI: Watt per Kelvin, W K(^-1) )
4) Thermal Contact Conductance per Unit Area (in SI: Watt Per Meter Squared Per Kelvin, W m(^-2) K(^-1) )
5) Specific Heat Capacity (in SI: Joule per Kilogram per Kelvin, J kg(^-1) K(^-1) )

To be able to extend the system model to store thermal properties, these units are needed.

**Comment by SaMuellerDLR** [comment]
@heibhe We seem to create the default units using the SI units of the following base quantifies
```
//create the 8 SI base QuantityKinds as reference in the helper class	
dimensionlessQK = createSimpleQuantityKind(DIMENSIONLESS_QK_NAME, "U", "dimensionlessQK", "");
length = createSimpleQuantityKind("Length", "L", "lengthQK", "");
mass = createSimpleQuantityKind("Mass", "M", "massQK", "");
time = createSimpleQuantityKind("Time", "T", "timeQK", "");
temperature = createSimpleQuantityKind("Temperature", "Θ", "temperatureQK", "");
amountOfSubstance = createSimpleQuantityKind("Amount of substance", "N", "amountOfSubstanceQK", "");
electricCurrent = createSimpleQuantityKind("Electric current", "I", "electricCurrentQK", "");
luminousIntensity = createSimpleQuantityKind("Luminous intensity", "J", "luminousIntensityQK", "");
```
Could you give the unit definitions using these base quantities ?
Then I can add them without breaking previous conventions.

I think I also need the unit symbol and name.
The ones you wrote down seem to be physical quantities instead of units.
Am I seeing this right?

**Comment by heibhe** [comment]
@SaMuellerDLR 
You are right, they are all quantities not units. They have no own unit. Thus, there is no unit name nor symbol. The quantities represented by base quantities would be: 
1. Thermal Conductivity (in base quantities: M * L * T^(-3) * Θ^(-1) )
2. Thermal Contact Resistance (in base quantities: T^3 * Θ * M^(-1) * L^(-2) )
3. Thermal Contact Conductance (in base quantitites: M * L^2 * T^(-3) * Θ^(-1) )
4. Thermal Contact Conductance per Unit Area (in base quantities: M * T^(-3) * Θ^(-1))
5. Specific Heat Capacity (in base units: L^2 * T^(-2) * Θ^(-1) )

Quantity 2 is not that important, as it is an inverse of Quantitiy 3. Thus 1,2,4 and 5 would be sufficient.
