### ISSUE TITLE
F2 for renaming objects in the navigator and the tables

### ISSUE THREAD

**Issue by SaMuellerDLR** [virtualsatellite/VirtualSatellite4-Core#775]
Implement the standard functionality for renaming objects in the navigator and for entering editing mode in tables using the F2 key.

**Comment by franzTobiasDLR** [comment]
I remember this place to catch keboard events in the table:

- https://github.com/virtualsatellite/VirtualSatellite4-Core/blob/25af0ab28b6ba5abbe14545b48a1cd1c1b1b6a09/de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericTable.java#L302
