### ISSUE TITLE
Reference & Resource properties cannot be reset to null

### ISSUE THREAD

**Issue by franzTobiasDLR** [virtualsatellite/VirtualSatellite4-Core#822]
Currently it is not possible (at least I didn't find a way) to clear a reference... If nothing is selected in the reference selection dialog then it returns null, which is of cause not of type ATypeInstance, so it's rejected...

Should we have a button "Clear" here? Or enable the set command to be executed with null?

**Comment by franzTobiasDLR** [comment]
@PhilMFischer @andriikovalov-dlr  What's your opinon on that?

**Comment by franzTobiasDLR** [comment]
Refereing to this line: https://github.com/virtualsatellite/VirtualSatellite4-Core/blob/17c5a8bec18cc30f41cf08b5d09d9b2b5c018dcb/de.dlr.sc.virsat.uiengine.ui/src/de/dlr/sc/virsat/uiengine/ui/editor/snippets/AUiSnippetGenericPropertyInstances.java#L898

**Comment by franzTobiasDLR** [comment]
Decided to create a button for a more intituve UI...

**Comment by andriikovalov-dlr** [comment]
Nice, I like it 👍
