### ISSUE TITLE
Local surefire build erroring because of server test cases

### ISSUE THREAD

**Issue by ghost** [virtualsatellite/VirtualSatellite4-Core#970]
Some weird connection exception occurs when using maven surfire on the local mashine. Maybe this has something to do with firewall configurations?

![grafik](https://user-images.githubusercontent.com/56025440/111782305-25d55f80-88b9-11eb-88d7-d653798c2c4c.png)

**Comment by PhilMFischer** [comment]
Solved with release 4.17
