### ISSUE TITLE
Prepare functionality to easily update the QUDV model with new units

### ISSUE THREAD

**Issue by PhilMFischer** [virtualsatellite/VirtualSatellite4-Core#99]
Some often used units are not present e.g milli seconds.

In case a projects adds new Units and values it should be easy to export them from one project and to update them in another one.

**Comment by SaMuellerDLR** [comment]
There exists an implementation. Should review it.

**Comment by andriikovalov-dlr** [comment]
QUDV import doesn't work, created a separate issue #664
